### ISSUE TITLE
Using body tracking SDK version > 0.9.5 fails to create tracker 

### ISSUE THREAD

**Issue by GCourtney27** [wouterverweirder/kinect-azure#11]
When using an SDK version 0.9.5 or higher for body tracking, this error occurs and clicking another demo tab completely crashes the application. 
![Electron_Renderer_Crash](https://user-images.githubusercontent.com/38294509/73579773-a4b2d300-4440-11ea-9602-620da37aa1ac.PNG)
Some things I tried to fix the issue are:
* Different combinations of API versions (tracker, body tracker, body tracker dependencies, dependencies cudnn)
* Attaching debugger thread to active process in vs2017
* Throwing exceptions to js from C
* Catching js exceptions in js and catching exceptions in C
* Logging to files k4a log system and C ofstream (doesn't work)
* Setting-up debugger in vs code to debug attached C code in electron (requires a built exe, this app does not build an exe)
* Not throwing exceptions and just printing. Seeing if user exceptions are the problem (one method fails the whole app stops ie nothing prints)
* Checked to make sure image formats didn't change (they didn't, this method is the culprit)

**Comment by wouterverweirder** [comment]
The current version is built for SDK version 0.9.4 - follow up in issue #8
