### ISSUE TITLE
listening to log events

### ISSUE THREAD

**Issue by peteshand** [wouterverweirder/kinect-azure#14]
Hey I'm wanting to listen to logs from c++ and noticed that you already have some logs hooked up. Eg:
```
g_emit.Call({Napi::String::New(env, "log"), Napi::String::New(env, "openPlayback")});
```
and you have an EventEmitter in lib/kinect-azure.js
```
constructor() {
    const emitter = new EventEmitter();
    kinect.init(emitter.emit.bind(emitter));
  }
```
This is feature complete? I just can't work out how to log to the console without modifying emitter to be public, or changing the constructor to something like:
```
constructor() {
    const emitter = new EventEmitter();
    kinect.init(emitter.emit.bind(emitter));
    emitter.on('log', (data) => {
      console.log("[kinect_azure.cc] " + data);
    });
  }
```

**Comment by wouterverweirder** [comment]
That's some debug code lingering around, which I used to send log messages from the C++ code to javascript. It's not meant to use outside of the kinect-azure lib. I'm nog using this anymore and should remove this from the source code. When trying things, I'm just doing `printf("[kinect_azure.cc] beep beep\n");` in the C code, which logs to the terminal.
