### ISSUE TITLE
Camera is not mirror image

### ISSUE THREAD

**Issue by Chrisbright10** [wouterverweirder/kinect-azure#2]
the image returned from the camera is horizontally flipped (e.g. raising the right arm raises the left arm on the screen). Can we get the image to return in a regular mirrored format?

Note: the default Kinect viewer that ships with the SDK outputs the view in a mirrored format.

**Comment by wouterverweirder** [comment]
Hi Chris,

Thanks for your question. I just reviewed the default Kinect Viewer and I'm not seeing a mirrored image there. Also, the sensor SDK doesn't seem to provide a mirroring option.

If you need mirroring in your viewer. I would suggest doing this through CSS (transforms) or swapping pixel indices when working with the raw feeds?

**Comment by Chrisbright10** [comment]
Hi,

I noticed that the latest version of the kinect viewer is not mirrored either, (maybe it changed? Or maybe I am thinking of the Kinect v2 since I switch between them often). 

I will definitely play with the output to try and mirror it. In the meantime, I would love it if you could include an example of mirrored output in the examples! (I am doing mirrored color output with bodytracking) But keep it with the good work! This is an awesome project!

**Comment by Chrisbright10** [comment]
The easiest was a CSS transform as shown in this article, thanks!
https://stackoverflow.com/questions/3129099/how-to-flip-images-horizontally-with-html5
