### ISSUE TITLE
Add support to gyroscope data

### ISSUE THREAD

**Issue by JpEncausse** [wouterverweirder/kinect-azure#22]
Hello,
Thanks for all the work done !
Would it be possible to stream Gyroscope data in order to detect ceil/roof while playing with body coordinates ? FOr instance this would help to align a 3D modèle

**Comment by wouterverweirder** [comment]
Added - [check out an example on how to use this data](https://github.com/wouterverweirder/kinect-azure/blob/master/examples/electron/renderer/demos/temp-acc-gyro.html)
