### ISSUE TITLE
Electron Builder doesn't package this correctly & Body tracking doesn't work

### ISSUE THREAD

**Issue by TomByrne** [wouterverweirder/kinect-azure#36]
We're using Vue + Electron Builder to package an app that uses this.

By default, the resulting package is about 900mb larger than it needs to be, because it includes a bunch of artifacts that aren't required at runtime.
I'm guessing there is a way to exclude this folder via kinect-azure/package.json or something, sorry I'm not fully sure.

Also without extra configuration, the body tracking doesn't work, it looks like the DLLs for this do get included in the package, but in the wrong location. Again, I'm not really sure how to fix this in this lib, although I'm fairly sure there's a way.

For others with this issue, this is how we resolved it at a project level:
```js
// In vue.config.js
module.exports = {
  ...
  pluginOptions: {
    electronBuilder: {
      // required to enable the node kinect api in electron
      nodeIntegration: true,
      builderOptions: {
        files: [
          "**",

          // Reduce the package size by omitting some kinect artifacts
          "!**node_modules/kinect-azure/sdk/**",
          "!**node_modules/kinect-azure/examples/**",
          "!**node_modules/kinect-azure/*.onnx",

          // These DLLs are required but get included in the wrong location by default
          "!**node_modules/kinect-azure/*.dll"
        ],
        extraFiles: [
          // Re-include the DLLs in the correct location (i.e. the root)
          {
            from: "node_modules/kinect-azure",
            to: "",
            filter: ["*.dll"]
          }
        ]
      }
    }
  }
};
```

**Comment by wouterverweirder** [comment]
Thanks for the report.

I made quite a few changes to the build process, while updating to the latest body tracking SDK + moved to precompiled binaries for this library.

As the body tracking sdk dependencies is becoming quite a list of necessary dlls - the recommended approach is now downloading the SDK manually and either adding the SDK to your path OR copying the dlls into your application.
