### ISSUE TITLE
Minor lag in response when body tracking is enabled

### ISSUE THREAD

**Issue by Chrisbright10** [wouterverweirder/kinect-azure#4]
Turning on body tracking makes the code lag and run slowly. It seems to be related only to body tracking. The Kinect viewer code doesn't seem to have this issue, so I assume it is something in the nan code.

**Comment by wouterverweirder** [comment]
Thanks for the bug report! There was a performance issue indeed, I was doing a blocking call in the the C code to get the tracking results, which caused the code to slow down a lot.

Just published an update (0.0.7) which should fix this issue.

**Comment by Chrisbright10** [comment]
Thanks! I will test it out and keep you updated!

**Comment by Chrisbright10** [comment]
Looks awesome! Great job.
