### ISSUE TITLE
Feature request: Multisource implementation

### ISSUE THREAD

**Issue by lisajamhoury** [wouterverweirder/kinect-azure#42]
Hello again! Do you plan to implement multisource for kinect-azure? 

Thanks.

**Comment by wouterverweirder** [comment]
Hi Lisa! Do you mean multiple streams (color + depth + ....) at once? I think this feature is covered. Or do you mean multiple Kinects? Only have access to one device, so can't implement and test this.

**Comment by lisajamhoury** [comment]
Hi Wouter, Sorry I missed this message back in May. Yes I meant multiple streams at once. But yes I am seeing now that this is already implemented. Sorry about that, I was coming from your Kinect2 package and looking for the same  "multiSourceFrame." Pandemic brain 🤪 Closing now.
