### ISSUE TITLE
D:\package.jsondoes not exist

### ISSUE THREAD

**Issue by diegocostaskii** [wouterverweirder/kinect-azure#44]
i tried to import it into my react-electron project then it comes out.
![image](https://user-images.githubusercontent.com/55731774/118356373-95a95300-b5a7-11eb-8503-e0243000cc3d.png)

**Comment by diegocostaskii** [comment]
by the way, i write an empty .d.ts to use it in ts env maybe that's the reason

**Comment by diegocostaskii** [comment]
what is binding_path？ how can i manualy add it

**Comment by wouterverweirder** [comment]
Looks like it's an issue with using a bundler such as webpack, in combination with node-pre-gyp:

- https://github.com/mapbox/node-pre-gyp/issues/308

Maybe the approach in that issue fixes your problem?

**Comment by diegocostaskii** [comment]
thanks ，i had fix it by manualy add the path （to .node）
