### ISSUE TITLE
Typescript support (d.ts)

### ISSUE THREAD

**Issue by challenger71498** [wouterverweirder/kinect-azure#46]
Above all, thank you for creating this amazing asset.

# Issues

Since I am developing with Typescript environment, I need a declaration file to specify the type of data output when listening.

# Solution

I made my own d.ts temporarily [here](https://gist.github.com/challenger71498/f4756d3f12cc19ceb291ed5ca9fb5e52), so if anyone needs type definition can use this.

I would like to contribute this file, but I don't really know how to. Should I PR this? Or create a @types/kinect-azure sth like that?

**Comment by wouterverweirder** [comment]
Hi there,

Thanks for that! Haven't worked with Typescript yet, but I can see how this is useful. Will look into this, if this doesn't add extra dependencies to this project, I'm all up for adding the type definitions to this repo.

**Comment by challenger71498** [comment]
Thanks for quick reply!

Nope, it has no dependencies at all, so totally fine for adding it on the repo!

**Comment by wouterverweirder** [comment]
Cool - could you create a pull request, with your kinect-azure.d.ts in the lib folder (next to Kinect-azure.js) and I'll merge it.

**Comment by challenger71498** [comment]
Thank you for quick reply!

I just created a PR on it :) glad that I can contribute to this amazing repo!

**Comment by wouterverweirder** [comment]
Thanks a lot for contributing this! Merged :-)
