### ISSUE TITLE
Typescript definition of ImageFrame is missing deviceTimestamp and systemTimestamp

### ISSUE THREAD

**Issue by wouterverweirder** [wouterverweirder/kinect-azure#54]
These extra properties were added in https://github.com/wouterverweirder/kinect-azure/commit/7abea234edbdab1c7c771cf5539bd0e2931842dc

**Comment by challenger71498** [comment]
Thank you for the issue! I'll add those and PR again :)

**Comment by challenger71498** [comment]
Created PR at #55 here!

Also fixed mismatched module name.
