### ISSUE TITLE
Manual Exposure

### ISSUE THREAD

**Issue by JpEncausse** [wouterverweirder/kinect-azure#9]
How can I set the Kinect Exposure to Manual ?
I see on the recorder there is an option, but I don't see / understand how to use it in the bindings
Thanks !

**Comment by wouterverweirder** [comment]
It's not in this library yet - but will add it to my todo list for next week :-)

**Comment by JpEncausse** [comment]
Thanks great !

**Comment by JpEncausse** [comment]
> It's not in this library yet - but will add it to my todo list for next week :-)

If you have time would be awesome !

My usecase is to perform computer vision on image stream. But dynamic exposure change the color of things (even with HSL) and it becomes very hard to track an object.

Thanks !

**Comment by wouterverweirder** [comment]
Not done yet, for my own reference: will need to check https://microsoft.github.io/Azure-Kinect-Sensor-SDK/master/group___functions_gae81269489170b26b7f0bbe1a7f9d31d6.html#gae81269489170b26b7f0bbe1a7f9d31d6

**Comment by JpEncausse** [comment]
Yes the implementation on the SDK recorder tool args is :
- a boolean yes/no to activate the autofocus
- an int with the exposure value

**Comment by wouterverweirder** [comment]
added in version 0.0.13, thanks to @peteshand's work - also added a demo (color controls) showing this new feature.
